name: Publish Changelog

# dispatch inputs are reversed for a reason, here's why:
# workflow dispatch is the only event with an inputs context,
# which means only that context is able to do the ifs properly
# now github likes to coerce types to a number, and if i
# understand correctly nil evaluates to a 0, aka false
# this means that we can make the if condition require an
# explicit 1 to not run
# === TLDR === 
# others dont have inputs, so it evalutes 
# to nil and then to zero, aka false.
# this means stuff is disabled by turning it on, which
# makes auto runs possible

on:
  workflow_dispatch:
    inputs:
      publish_discord:
        description: 'Disable publish to Discord'
        default: false
        type: boolean
      publish_rss:
        description: 'Disable publish to RSS'
        default: false
        type: boolean
  schedule:
  - cron: 0 14 * * 5

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v4.2.2

    - name: Publish changelog (Discord)
      if: ${{ !inputs.publish_discord }}
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

    - name: Publish changelog (RSS)
      if: ${{ !inputs.publish_rss }}
      run: Tools/actions_changelog_rss.py
      env:
        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
