name: Publish Changelog

on:
  workflow_dispatch:
    inputs:
      publish_discord:
        description: 'Publish to Discord'
        default: true
        type: boolean
      publish_rss:
        description: 'Publish to RSS'
        default: true
        type: boolean
  schedule:
  - cron: 0 14 * * 5

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v4.2.2

    - name: Publish changelog (Discord)
      if: ${{ inputs.publish_discord }}
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

    - name: Publish changelog (RSS)
      if: ${{ inputs.publish_rss }}
      run: Tools/actions_changelog_rss.py
      env:
        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
